{{- if .Values.frontendRequester.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpdesk.fullname" . }}-frontend-requester
  labels:
    app.kubernetes.io/name: {{ include "helpdesk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend-requester
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helpdesk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend-requester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helpdesk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend-requester
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontendRequester.image.repository }}:{{ .Values.frontendRequester.image.tag }}"
          imagePullPolicy: {{ .Values.frontendRequester.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
{{- end }}
