{{- if and .Values.secrets.enabled (not .Values.secrets.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpdesk.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "helpdesk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}

