# Build
FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
WORKDIR /src/cmd/worker
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/worker
# Run
FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/worker /worker
USER nonroot:nonroot
ENTRYPOINT ["/worker"]
