# Build
FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
WORKDIR /src/cmd/api
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/api
# Run
FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/api /api
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/api"]
