# Build
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY worker/cmd/worker/ ./worker/cmd/worker/
WORKDIR /src/worker/cmd/worker
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/worker
# Run
FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/worker /worker
USER nonroot:nonroot
ENTRYPOINT ["/worker"]
