image:
  repository: ghcr.io/mark3748/helpdesk-go-api
  tag: latest
  pullPolicy: IfNotPresent

# Internal frontend (optional)
frontendInternal:
  enabled: true
  image:
    repository: ghcr.io/mark3748/helpdesk-go-internal-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

# Requester frontend (optional, separate ingress)
frontendRequester:
  enabled: false
  image:
    repository: ghcr.io/mark3748/helpdesk-go-requester-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

workerImage:
  repository: ghcr.io/mark3748/helpdesk-go-worker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: helpdesk.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
        - path: /swagger
          pathType: Prefix
  tls: []

# Separate ingress for requester portal (optional)
ingressRequester:
  enabled: false
  className: nginx
  apiProxy: true
  hosts:
    - host: requester.helpdesk.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  ENV: "prod"
  ADDR: ":8080"
  # CORS: allow origins for UIs calling the API (comma-separated)
  ALLOWED_ORIGINS: ""
  # External services (set to your endpoints)
  DATABASE_URL: "postgres://user:pass@postgres:5432/helpdesk?sslmode=disable"
  REDIS_ADDR: "redis:6379"
  # Timeouts (ms)
  REDIS_TIMEOUT_MS: "2000"
  OBJECTSTORE_TIMEOUT_MS: "10000"
  # API auth (optional)
  AUTH_MODE: "oidc"
  AUTH_LOCAL_SECRET: ""
  OIDC_ISSUER: ""
  OIDC_JWKS_URL: ""
  # Object storage (optional)
  MINIO_ENDPOINT: ""
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
  MINIO_BUCKET: ""
  MINIO_USE_SSL: "false"
  # Worker email/IMAP (optional)
  SMTP_HOST: ""
  SMTP_PORT: "25"
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: ""
  IMAP_HOST: ""
  IMAP_USER: ""
  IMAP_PASS: ""
  IMAP_FOLDER: "INBOX"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

# Pull secrets for private registries (e.g., GHCR)
imagePullSecrets: []
  # - ghcr-pull

# Optional Kubernetes Secret support for sensitive env vars
secrets:
  enabled: false
  # If you already have a Secret, set its name here and it will be referenced.
  # When empty and enabled=true, this chart will create a Secret named
  # "{{ include \"helpdesk.fullname\" . }}-secret" with the key/values below.
  name: ""
  data: {}
  # Example:
  # data:
  #   DATABASE_URL: "postgres://user:pass@postgres:5432/helpdesk?sslmode=disable"
  #   AUTH_LOCAL_SECRET: "super-secret"
  #   ADMIN_PASSWORD: "admin"

# Optional persistence for FILESTORE_PATH (filesystem object store)
persistence:
  enabled: false
  mountPath: "/data"
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClass: ""
  existingClaim: ""
