name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        name: [api, worker, internal-frontend, requester-frontend]
        platform: [linux/amd64, linux/arm64]
        include:
          - name: api
            file: Dockerfile.api
          - name: worker
            file: Dockerfile.worker
          - name: internal-frontend
            file: Dockerfile.frontend-internal
          - name: requester-frontend
            file: Dockerfile.frontend-requester
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.name }} image for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.name }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-${{ matrix.name }}:latest
          provenance: false
          sbom: false
