name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: api
            file: Dockerfile.api
          - name: worker
            file: Dockerfile.worker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.name }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-${{ matrix.name }}:latest
